# Generated by Django 4.1.13 on 2024-10-19 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroEmpresa',
            fields=[
                ('ID_registro', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_empre', models.CharField(max_length=255)),
                ('Correo', models.EmailField(max_length=254, unique=True)),
                ('Contraseña', models.CharField(max_length=255)),
                ('Imagen', models.ImageField(upload_to='imagenes/')),
                ('Palabra_clave', models.CharField(max_length=255)),
            ],
        ),
    ]
