# Generated by Django 4.1.13 on 2024-10-16 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchwiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroempresa',
            name='Imagen',
            field=models.ImageField(upload_to='imagenes/'),
        ),
    ]
