# Generated by Django 4.1.13 on 2024-10-16 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchwiz', '0002_alter_registroempresa_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistroEmpresa',
        ),
    ]
